[package]
name = "clippy-sarif"
version = "0.2.20"
authors = ["Paul Sastrasinh <psastras@gmail.com>"]
edition = "2018"
description = "Convert clippy output to SARIF"
license = "MIT"
readme = "README.md"
keywords = ["sarif", "clippy", "cli"]
categories = ["command-line-utilities"]
homepage  = "https://psastras.github.io/sarif-rs/"
documentation = "https://docs.rs/clippy_sarif"
repository = "https://github.com/psastras/sarif-rs"

[badges]
github = { repository = "psastras/sarif-rs" }

[[bin]]
name = "clippy-sarif"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.44"
serde-sarif = { path = "../serde-sarif", version = "0.2.20", features = ["clippy-converters"] }

[dependencies.clap]
version = "3.0.0-rc.7"

[dev-dependencies]
version-sync = "0.9"
